# Generated by Django 5.0.7 on 2024-08-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rule_string', models.TextField()),
                ('root_node', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ASTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
                ('left_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_parent', to='ruleengine.astnode')),
                ('right_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_parent', to='ruleengine.astnode')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ruleengine.rule')),
            ],
        ),
    ]
