# Generated by Django 5.0.7 on 2024-08-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='root_node',
            new_name='ast',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rule_string',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('result', models.BooleanField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleengine.rule')),
            ],
        ),
        migrations.DeleteModel(
            name='ASTNode',
        ),
    ]
